title: Blogston
author: Roxton Ma
email: roxtonmart@gmail.com
description: Not set in stone but out there.
baseurl: "/blog" # Repository name without "/" / Comment out during local testing and exposing network
encoding: utf-8
permalink: /:slug/
url: "https://roxtonma.github.io"

# Default post layout
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Roxton Ma" # Default author

# Exclude files from processing
exclude:
  - md-help.md
  - README.md
  - vendor/
  - Gemfile
  - Gemfile.lock
  - .github/

plugins:
  - jekyll-sitemap